/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package world;

import org.junit.Test;
import world.cpp.Synthesis;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        assertTrue("test",true);
    }
}
